import type { User, Order, UserRole } from './types';

export const mockUsers: Record<UserRole, User> = {
  admin: {
    name: 'Igor Rodriguez',
    email: 'admin@khlothia.pack',
    role: 'admin',
    avatarUrl: 'https://picsum.photos/seed/admin/100/100'
  },
  operations: {
    name: 'Operations User',
    email: 'ops@khlothia.pack',
    role: 'operations',
    avatarUrl: 'https://picsum.photos/seed/ops/100/100'
  },
  client: {
    name: 'Client User',
    email: 'client@khlothia.pack',
    role: 'client',
    avatarUrl: 'https://picsum.photos/seed/client/100/100'
  },
  courier: {
    name: 'Courier User',
    email: 'courier@khlothia.pack',
    role: 'courier',
    avatarUrl: 'https://picsum.photos/seed/courier/100/100'
  },
  finance: {
    name: 'Finance User',
    email: 'finance@khlothia.pack',
    role: 'finance',
    avatarUrl: 'https://picsum.photos/seed/finance/100/100'
  },
  warehouse: {
    name: 'Warehouse User',
    email: 'warehouse@khlothia.pack',
    role: 'warehouse',
    avatarUrl: 'https://picsum.photos/seed/warehouse/100/100'
  }
};

export const mockOrders: Order[] = [
  {
    id: '1',
    externalOrderReference: 'POD0001',
    client: 'Tienda Moda',
    status: 'Generado',
    recipientName: 'Ana García',
    recipientPhone: '809-111-2222',
    cashOnDeliveryAmount: 2500,
    createdAt: '2024-07-22T10:00:00Z',
    estadoDeEmpaque: 'Pendiente',
    paymentType: 'COD',
    deliveryAddress: { id: 'addr1', city: 'Santo Domingo', sector: 'Naco', province: 'DN', addressLine1: 'Calle Fantasía 123' },
  },
  {
    id: '2',
    externalOrderReference: 'POD0002',
    client: 'ElectroHogar',
    status: 'Confirmado',
    recipientName: 'Luis Jiménez',
    recipientPhone: '829-333-4444',
    cashOnDeliveryAmount: 15000,
    createdAt: '2024-07-22T11:30:00Z',
    estadoDeEmpaque: 'Empacado',
    paymentType: 'COD',
    deliveryAddress: { id: 'addr2', city: 'Santiago', sector: 'El Dorado', province: 'Santiago', addressLine1: 'Av. Estrella Sadhalá 45' },
  },
  {
    id: '3',
    externalOrderReference: 'POD0003',
    client: 'Libros & Café',
    status: 'En Ruta',
    recipientName: 'Carla Fernández',
    recipientPhone: '849-555-6666',
    cashOnDeliveryAmount: 850,
    createdAt: '2024-07-21T15:00:00Z',
    estadoDeEmpaque: 'Enviado',
    assignedCourierName: 'Pedro Martinez',
    paymentType: 'COD',
    deliveryAddress: { id: 'addr3', city: 'Santo Domingo', sector: 'Mirador Sur', province: 'DN', addressLine1: 'Av. Anacaona 78' },
  },
  {
    id: '4',
    externalOrderReference: 'POD0004',
    client: 'Tienda Moda',
    status: 'Entregado',
    recipientName: 'Sofía Reyes',
    recipientPhone: '809-777-8888',
    cashOnDeliveryAmount: 3200,
    createdAt: '2024-07-20T09:00:00Z',
    deliveredAt: '2024-07-20T14:30:00Z',
    estadoDeEmpaque: 'Enviado',
    assignedCourierName: 'Juan Castillo',
    paymentType: 'COD',
    deliveryAddress: { id: 'addr4', city: 'Punta Cana', sector: 'Bávaro', province: 'La Altagracia', addressLine1: 'Residencial Palma Real, Villa 15' },
  },
  {
    id: '5',
    externalOrderReference: 'POD0005',
    client: 'Juguetería Feliz',
    status: 'Novedad',
    recipientName: 'Mario Vargas',
    recipientPhone: '829-999-0000',
    cashOnDeliveryAmount: 1200,
    createdAt: '2024-07-21T12:00:00Z',
    estadoDeEmpaque: 'Enviado',
    assignedCourierName: 'Pedro Martinez',
    paymentType: 'COD',
    deliveryAddress: { id: 'addr5', city: 'Santo Domingo', sector: 'Gazcue', province: 'DN', addressLine1: 'Calle Moises Garcia 10' },
  },
  {
    id: '6',
    externalOrderReference: 'POD0006',
    client: 'ElectroHogar',
    status: 'Pendiente Respuesta',
    recipientName: 'Laura Gómez',
    recipientPhone: '809-222-3333',
    cashOnDeliveryAmount: 5500,
    createdAt: '2024-07-22T14:00:00Z',
    estadoDeEmpaque: 'Pendiente',
    paymentType: 'COD',
    deliveryAddress: { id: 'addr6', city: 'La Romana', sector: 'Centro', province: 'La Romana', addressLine1: 'Av. Libertad 22' },
  },
  {
    id: '7',
    externalOrderReference: 'POD0007',
    client: 'Libros & Café',
    status: 'Devolución',
    recipientName: 'Carlos Santana',
    recipientPhone: '849-111-9999',
    cashOnDeliveryAmount: 1750,
    createdAt: '2024-07-19T11:00:00Z',
    estadoDeEmpaque: 'Enviado',
    assignedCourierName: 'Juan Castillo',
    paymentType: 'COD',
    deliveryAddress: { id: 'addr7', city: 'Santo Domingo', sector: 'Zona Colonial', province: 'DN', addressLine1: 'Calle Las Damas 1' },
  },
  {
    id: '8',
    externalOrderReference: 'POD0008',
    client: 'Tienda Moda',
    status: 'Confirmado para la tarde',
    recipientName: 'Elena Duarte',
    recipientPhone: '809-888-7777',
    cashOnDeliveryAmount: 950,
    createdAt: '2024-07-22T09:30:00Z',
    estadoDeEmpaque: 'Pendiente',
    paymentType: 'COD',
    deliveryAddress: { id: 'addr8', city: 'Santo Domingo', sector: 'Bella Vista', province: 'DN', addressLine1: 'Av. Sarasota 55' },
  },
  {
    id: '9',
    externalOrderReference: 'POD0009',
    client: 'Juguetería Feliz',
    status: 'Cancelado',
    recipientName: 'Roberto Abreu',
    recipientPhone: '829-666-5555',
    cashOnDeliveryAmount: 2100,
    createdAt: '2024-07-20T18:00:00Z',
    estadoDeEmpaque: 'Pendiente',
    paymentType: 'COD',
    deliveryAddress: { id: 'addr9', city: 'San Cristóbal', sector: 'Centro', province: 'San Cristóbal', addressLine1: 'Calle Constitución 80' },
  },
  {
    id: '10',
    externalOrderReference: 'POD0010',
    client: 'ElectroHogar',
    status: 'Generado',
    recipientName: 'Patricia Cruz',
    recipientPhone: '809-444-1111',
    cashOnDeliveryAmount: 8900,
    createdAt: '2024-07-22T16:00:00Z',
    estadoDeEmpaque: 'Pendiente',
    paymentType: 'COD',
    deliveryAddress: { id: 'addr10', city: 'Boca Chica', sector: 'Playa', province: 'Santo Domingo', addressLine1: 'Duarte 101' },
  },
];
