// This file is autogenerated by Firebase AppHosting plugin.
"use client";
import React, { ReactNode, useEffect, useState } from "react";
import { initializeApp, getApp, getApps, FirebaseApp } from 'firebase/app';
import { getAuth, Auth } from 'firebase/auth';
import { getFirestore, Firestore } from 'firebase/firestore';
import { getStorage, FirebaseStorage } from "firebase/storage";
import { firebaseConfig } from "./client";
import { FirebaseContext } from "./context";

export function FirebaseProvider({ children }: { children: ReactNode }) {
    const [app, setApp] = useState<FirebaseApp | undefined>(undefined);
    const [auth, setAuth] = useState<Auth | undefined>(undefined);
    const [firestore, setFirestore] = useState<Firestore | undefined>(undefined);
    const [storage, setStorage] = useState<FirebaseStorage | undefined>(undefined);

    useEffect(() => {
        if (firebaseConfig.apiKey) {
            const appInstance = getApps().length === 0 ? initializeApp(firebaseConfig) : getApp();
            setApp(appInstance);
            setAuth(getAuth(appInstance));
            setFirestore(getFirestore(appInstance));
            setStorage(getStorage(appInstance));
        } else {
            console.error("Firebase API Key is missing. Please set NEXT_PUBLIC_FIREBASE_API_KEY in your environment.");
        }
    }, []);

    return (
        <FirebaseContext.Provider value={{ app, auth, firestore, storage }}>
        {children}
        </FirebaseContext.Provider>
    );
}
