// This file is autogenerated by Firebase AppHosting plugin.
"use client";
import React, { ReactNode } from "react";
import { app, auth, firestore } from "./client";
import { FirebaseContext } from "./context";

export function FirebaseProvider({ children }: { children: ReactNode }) {
  return (
    <FirebaseContext.Provider value={{ app, auth, firestore }}>
      {children}
    </FirebaseContext.Provider>
  );
}
